export {
  LABEL_TEXT_ALLIES as RELATION_ALLIES,
  LABEL_TEXT_AFFILIATES as RELATION_AFFILIATES,
  LABEL_TEXT_COLD_WARS as RELATION_COLD_WARS,
  LABEL_TEXT_ENEMIES as RELATION_ENEMIES,
  LABEL_TEXT_FRIENDS as RELATION_FRIENDS,
  LABEL_TEXT_HOT_WARS as RELATION_HOT_WARS,
} from '../../../config/strings';
export const RELATION_HAS_BENCH = 'has bench';
export const RELATION_HAS_LAB = 'has lab';
