export const RESPONSIVE_BREAKPOINT = 768;
export const BASE_SPACING = 4;
export const BASE_FONT_SIZE = 16;

export const ONE_SECOND_IN_MILLISECONDS = 1000;
export const ONE_MINUTE_IN_MILLISECONDS = ONE_SECOND_IN_MILLISECONDS * 60;
export const ONE_HOUR_IN_MILLISECONDS = ONE_MINUTE_IN_MILLISECONDS * 60;
export const ONE_DAY_IN_MILLISECONDS = ONE_HOUR_IN_MILLISECONDS * 24;
export const HALF_DAY_IN_MILLISECONDS = ONE_HOUR_IN_MILLISECONDS * 12;
